name: money_expert
description: A new Flutter project for managing financial matters.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  pmvvm: ^3.0.0
  lints: ^1.0.1
  percent_indicator: ^3.0.1
  shared_preferences: ^2.0.6
  flutter_easyloading: ^3.0.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.9
  font_awesome_flutter: ^9.0.0
  easy_localization: any
  firebase_core: ^1.7.0
  google_fonts: ^2.3.1
  firebase_performance: ^0.8.0+3
  firebase_remote_config: ^1.0.3
  firebase_crashlytics: ^2.5.3
  flutter_fadein: ^2.0.0
  day_night_switcher: ^0.2.0+1
  theme_manager: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/translations/
    - assets/images/
    - assets/files/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
